### ISSUE TITLE
Not respecting vscode exclusions

### ISSUE THREAD

**Issue by RichardFurness** [theia-ide/yang-vscode#10]
The "Files: Exclude" setting in vscode is not being respected. This causes problems like duplicate definitions if a workspace has symlinks that make files appear in multiple locations (e.g. due to using a build system such as bazel).

**Comment by JanKoehnlein** [comment]
The Xtext-based language server doesn't know that it runs in VSCode, and I am not aware of a language server protocol option to set excluded files.

Did you try https://github.com/theia-ide/yang-lsp/blob/master/docs/Settings.md#excluded-paths ?

**Comment by RichardFurness** [comment]
Hi Jan,

I tried this but can't get it to work. I know the yang.settings file is being picked up because I've tried adding other settings to it (specifically, code-lenses: off) and that worked fine. But my excludePaths setting just isn't having any effect. I'm using a multi-folder workspace, and I've tried all of the following:
- Putting the settings in ~/.yang and using an absolute excludePath
- Putting the settings in the root of the relevant folder and using a path relative to that folder
- Putting the settings in the parent of the folder (which is where my workspace file lives) and using a path relative to the parent, or to the folder

I'm using remote-ssh in vscode in case that's relavant (but I'm not sure why it would be).

Any ideas why it's not working?

**Comment by JanKoehnlein** [comment]
You may have to restart VS Code in order to pick up the changes in `yang.settings`.
I tried the following and it worked:
- Checked out [yang-lsp](https://github.com/theia-ide/yang-lsp)
- Ran the gradle build. This produces duplicates of all test files in the `build` folders
- Opened `yang-lsp/io.typefox.yang.ide` in VS Code
- Opened the file `src/test/resources/good/yt6.yang`
- Watch the output of the LS to finish validation -> No error pops up
Then
- Clear the `excludePath` in `yang.settings` in the root of the workspace by assigning an empty string
- Restart VS Code
- After the validation has finished, there is now a warning on duplicates in `yt6.yang`

Note that
- the syntax of excludePath is UNIX style, workspace relative, i.e. colon `:` to separate directories, slash `/` as file separator, no leading slashes `/`

**Comment by JanKoehnlein** [comment]
PS: I've never tried that with remote-ssh. Let me know if it works.

**Comment by RichardFurness** [comment]
Hi Jan,

I eventually figured this out after comparing your repro to mine: the issue is that I'd followed the instructions on here: https://github.com/theia-ide/yang-lsp/blob/master/docs/Settings.md

Which say that the config item is called "excludePaths". It turns out that it only works if you call it "excludePath"...

Seems like "excludePaths" would be a better name!

Cheers,

Richard

**Comment by JanKoehnlein** [comment]
Changed the docs to not break existing clients.
